name: 'First composite action'
description: 'unit test result comment'
inputs:
  xml-path:  # id of input
    description: 'your path to xml junit result'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - run: dart.sh '${{ inputs.xml-path }}'
      shell: bash
    - name: Add comment
      uses: machine-learning-apps/pr-comment@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: dart_action/output/result.txt